.\# Manpage for Nhance

.TH man 8 "15 Jul 2021" "1.1" "Nhance manual page"
.SH NAME
Ninc \- Narthex enhancer
.SH SYNOPSIS
cat dictionary.txt | nhance [OPTIONS] > output.txt
nhance [OPTIONS] dictionary.txt
.SH DESCRIPTION
Nhance reads from standard input or a file and appends to it the lines capitalized. It prints to standard output.

.SH OPTIONS
-f	Append full capitalizations as well

-v	print version and exit

-h	print help panel and exit

.SH AUTHOR
Michael Constantine Dimopoulos <mk@mcdim.xyz>

https://mcdim.xyz

.SH LICENSE
GNU Public License 3.0 (GPL-3.0)
