.\" Manpage for ncom

.TH man 8 "26 Jul 2021" "1.1.2" "ncom manual page"
.SH NAME
ncom \- Narthex combinator
.SH SYNOPSIS
cat dictionary.txt | ncom [OPTIONS] > output.txt
ncom dictionary.txt [OPTIONS] > output.txt
.SH DESCRIPTION
ncom iterates over stdin and after printing the dictionary as is, it will print it again but will also append every line of stdin to each iteration creating, that way, a list of combinations (pairs) of the lines.

.SH OPTIONS
-d	use dot separator

-u	use underscore separator

-m	use hyphen separator

-n	exclude numerical bases, so if the base is '2002' and the part to be appended is 'word', the operation will not be executed.

-b	do not operate when the base is the same with the appended part

-v	print version and exit

-h	print help panel and exit

.SH AUTHOR
Michael Constantine Dimopoulos <mk@mcdim.xyz>

https://mcdim.xyz

.SH LICENSE
GNU General Public License 3.0 (GPL-3.0)
