.\" Manpage for Ninc 

.TH man 8 "15 Jul 2021" "1.0" "Ninc manual page"
.SH NAME
Ninc \- Narthex incrementor
.SH SYNOPSIS
cat dictionary.txt | ninc [MIN] [MAX] [OPTIONS] > output.txt
.SH DESCRIPTION
Ninc reads from standard input and multiplies each line with the difference of max-min, and appends n to each line, where n is increased after every line from min to max inclusive. It prints to standard output.

.SH OPTIONS
-n	increment numerical lines

-v	print version and exit

-h	print help panel and exit

.PP
Notice, numerical lines (in this case 1234) are excluded. In order to include them you can use the -n option.

.SH AUTHOR
Michael Constantine Dimopoulos <mk@mcdim.xyz>

https://mcdim.xyz

.SH LICENSE
GNU Public License 3.0 (GPL-3.0)
