.\" Manpage for nhance

.TH man 8 "15 Jul 2021" "1.3.1" "nhance manual page"
.SH NAME
ninc \- Narthex enhancer
.SH SYNOPSIS
cat dictionary.txt | nhance [OPTIONS] > output.txt
nhance [OPTIONS] dictionary.txt
.SH DESCRIPTION
nhance reads from standard input or a file and appends to it the lines capitalized. It prints to standard output.

.SH OPTIONS
-f	append full capitalizations as well

-v	print version and exit

-h	print help panel and exit

.SH AUTHOR
Michael Constantine Dimopoulos <mk@mcdim.xyz>

https://mcdim.xyz

.SH LICENSE
GNU General Public License 3.0 (GPL-3.0)
